### ISSUE TITLE
[스프링] spring tomcat max_connection시 thread 관리

### ISSUE THREAD

**Issue by sean-k1** [KakaoEnt-Study/Effective-Java-Study#2]
혹시 spring 에서 **tomcat**의 허용 max_connection + 작업큐 이상의 thread 요청에 대해 관리가 어떤식으로 이뤄지는 지 아시나요?

tomcat 8.0 전에는 `BIO connector` 그 이후는 `NIO connector`로 바뀌었다고 들었는데요.
```
server:
  tomcat:
    threads:
      max: 2 # 생성할 수 있는 thread의 총 개수
      min-spare: 2 # 항상 활성화 되어있는(idle) thread의 개수
    accept-count: 1 # max threads를 사용하고있을때 대기 작업 큐의 사이즈
```
위의 설정을 가진 spring 에 request를 4개 이상 보낸다면 `thread-worker` 2개 `작업-큐`에 1개가 꽉차고 더이상 `request`를 수용할 수 없어서 reuqest를 거절하는 게 맞는것 같을때 [참고링크]( https://velog.io/@sihyung92/how-does-springboot-handle-multiple-requests)를 보면 오류가 발생하지 않더라구요.

정확히 설명을 해주지않아서 궁금한데 혹시 이유를 아시는 분 있으실까요?

----
[tomcat](https://tomcat.apache.org/tomcat-7.0-doc/config/http.html#Introduction)
공식문서

Each incoming request requires a thread for the duration of that request. If more simultaneous requests are received than can be handled by the currently available request processing threads, additional threads will be created up to the configured maximum (the value of the maxThreads attribute). If still more simultaneous requests are received, they are stacked up inside the server socket created by the Connector, up to the configured maximum (the value of the acceptCount attribute). **Any further simultaneous requests** will receive **"connection refused"** errors, until resources are available to process them.
